### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by vikasverma1077** [vvvm23/vqvae-2#3]
hello, I am trying to run main-pixelsnail.py and it gives OOM error after executing batches. would you know what could be causing it? 
```
`python main-pixelsnail.py latent-data/cifar10_cifar10-state-dict-0008_2021-10-14_07-04-08_latent runs/cifar10-2021-10-14_06-35-07/checkpoints/cifar10-state-dict-0008.pt 0 --task cifar10
> Loading Latent dataset
/home/vermavik/vikas/lib/python3.8/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
> Initialising Model
> Epoch 1/100:
  0%|                                                                                                           | 0/391 [00:00<?, ?it/s]0
training loss: 6.2459635734558105 | accuracy: 0.2044677734375%:   0%|                                   | 1/391 [00:05<38:43,  5.96s/it]1
training loss: 6.245503187179565 | accuracy: 0.2166748046875%:   1%|▏                                   | 2/391 [00:06<18:51,  2.91s/it]2
training loss: 6.245569388071696 | accuracy: 0.19938151041666666%:   1%|▏                               | 3/391 [00:07<12:31,  1.94s/it]3
training loss: 6.24453592300415 | accuracy: 0.206756591796875%:   1%|▎                                  | 4/391 [00:08<09:35,  1.49s/it]4
training loss: 6.195447158813477 | accuracy: 0.595703125%:   1%|▌                                       | 5/391 [00:10<10:54,  1.70s/it]5
training loss: 6.164468129475911 | accuracy: 0.85296630859375%:   2%|▌                                  | 6/391 [00:11<08:52,  1.38s/it]6
training loss: 6.139556748526437 | accuracy: 1.0550362723214286%:   2%|▌                                | 7/391 [00:11<07:35,  1.19s/it]7
training loss: 6.1200403571128845 | accuracy: 1.2371063232421875%:   2%|▋                               | 8/391 [00:12<06:46,  1.06s/it]8
training loss: 6.1768646240234375 | accuracy: 1.2427435980902777%:   2%|▋                               | 9/391 [00:13<07:07,  1.12s/it]9
training loss: 6.222517967224121 | accuracy: 1.24359130859375%:   3%|▊                                 | 10/391 [00:14<06:26,  1.01s/it]10
training loss: 6.25629828192971 | accuracy: 1.2906161221590908%:   3%|▉                                | 11/391 [00:15<05:58,  1.06it/s]11
training loss: 6.284782528877258 | accuracy: 1.3117472330729167%:   3%|▉                               | 12/391 [00:16<05:39,  1.12it/s]12
training loss: 6.278294196495643 | accuracy: 1.3138991135817308%:   3%|█                               | 13/391 [00:17<05:59,  1.05it/s]13
training loss: 6.272128616060529 | accuracy: 1.3283865792410714%:   4%|█▏                              | 14/391 [00:18<05:38,  1.11it/s]14
training loss: 6.265336990356445 | accuracy: 1.3444010416666667%:   4%|█▏                              | 15/391 [00:18<05:24,  1.16it/s]15
training loss: 6.2589346170425415 | accuracy: 1.3620376586914062%:   4%|█▎                             | 16/391 [00:19<05:15,  1.19it/s]16
training loss: 6.2589346170425415 | accuracy: 1.3620376586914062%:   4%|█▎                             | 16/391 [00:22<08:55,  1.43s/it]
Traceback (most recent call last):
  File "main-pixelsnail.py", line 81, in <module>
    loss, accuracy, _ = trainer.train(x, c)
  File "/home/vermavik/github/vqvae-2/trainer.py", line 150, in train
    (loss / self.update_frequency).backward()
  File "/home/vermavik/vikas/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/vermavik/vikas/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 15.78 GiB total capacity; 13.42 GiB already allocated; 158.00 MiB free; 14.29 GiB reserved in total by PyTorch)
`
```

**Comment by vvvm23** [comment]
I'm somewhat uncertain why it OOMs after already completing some batches. Very strange~
You can reduce the `mini_batch_size` in `hps.py` (among other parameters) in order to reduce the memory requirements.

However, currently the generative PixelSnail priors (as I said in the README) are experimental and definitely not working yet, so I would not recommend using the PixelSnail main script anyway as it may not converge even with unlimited memory :)

In the future, I will be getting the PixelSnail model working.

**Comment by vikasverma1077** [comment]
Thanks for the reply. Yes, that is strange.

If I can not use PixelSnail priors, then is there any other code in this repo that can be used for sampling images?

**Comment by vvvm23** [comment]
Currently in this repo there is no way to sample images.

This is something I plan on doing in the future. It may not be a PixelSnail, but could be some kind of GPT model. However, I have other work that is of higher priority right now (:

Any generative model on discrete data should work though. Just give it the dataset of discrete latent codes.

Sorry that I couldn't be of more help ~
